"use client";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Loader2, Paperclip, Send } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

export default function NewTicketPage(){
 const [categories,setCategories]=useState<{id:string;name:string}[]>([]); const [subject,setSubject]=useState(""); const [description,setDescription]=useState(""); const [priority,setPriority]=useState("medium"); const [categoryId,setCategoryId]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{const s=createSupabaseBrowserClient(); if(s)s.from("categories").select("id,name").eq("is_active",true).order("name").then(({data})=>setCategories(data||[]));},[]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const s=createSupabaseBrowserClient();if(!s){setError("Supabase belum dikonfigurasi.");setLoading(false);return}const {data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return}const {data,error}=await s.from("tickets").insert({subject,description,priority,category_id:categoryId||null,customer_id:user.id}).select("id").single();if(error)setError(error.message);else window.location.href=`/tickets/${data.id}`;setLoading(false)}
 return <main className="form-page"><a className="back-link" href="/"><ArrowLeft size={16}/> Kembali ke dashboard</a><div className="form-card"><p className="eyebrow">Portal customer</p><h1 className="h1">Buat tiket baru</h1><p className="sub">Jelaskan kendala Anda secara lengkap agar tim kami dapat membantu lebih cepat.</p><form onSubmit={submit} className="ticket-form"><label>Subjek<input required minLength={3} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Contoh: Tidak dapat login ke aplikasi"/></label><div className="form-grid"><label>Kategori<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Pilih kategori</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Prioritas<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Rendah</option><option value="medium">Sedang</option><option value="high">Tinggi</option><option value="urgent">Urgent</option></select></label></div><label>Deskripsi<textarea required minLength={10} rows={8} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ceritakan kendala, langkah yang sudah dicoba, dan hasilnya..."/></label><div className="attachment-note"><Paperclip size={16}/> Lampiran akan tersedia setelah storage Supabase diaktifkan.</div>{error&&<p className="auth-error">{error}</p>}<button className="primary" disabled={loading}>{loading?<Loader2 className="spin" size={16}/>:<Send size={16}/>} Kirim tiket</button></form></div></main>
}
