"use client";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Loader2, Send } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Ticket={id:string;ticket_number:number;subject:string;description:string;status:string;priority:string;created_at:string;customer_id:string;category?:{name:string}|null}; type Message={id:string;body:string;is_internal:boolean;created_at:string;sender?:{full_name:string}|null};
export default function TicketDetail({params}:{params:{id:string}}){const [ticket,setTicket]=useState<Ticket|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [body,setBody]=useState("");const [loading,setLoading]=useState(true);const [sending,setSending]=useState(false);const [error,setError]=useState("");
 async function load(){const s=createSupabaseBrowserClient();if(!s)return;const {data,error}=await s.from("tickets").select("*,category:categories(name)").eq("id",params.id).single();if(error)setError(error.message);else {setTicket(data);const m=await s.from("ticket_messages").select("*,sender:profiles(full_name)").eq("ticket_id",params.id).order("created_at");setMessages(m.data||[])}setLoading(false)} useEffect(()=>{load()},[params.id]);
 async function send(e:FormEvent){e.preventDefault();if(!body.trim())return;setSending(true);const s=createSupabaseBrowserClient();if(!s)return;const {data:{user}}=await s.auth.getUser();if(!user)return;const {error}=await s.from("ticket_messages").insert({ticket_id:params.id,sender_id:user.id,body,is_internal:false});if(error)setError(error.message);else{setBody("");await load()}setSending(false)}
 if(loading)return <main className="form-page"><Loader2 className="spin"/></main>;if(!ticket)return <main className="form-page"><p className="auth-error">{error||"Tiket tidak ditemukan."}</p></main>;
 return <main className="form-page"><a className="back-link" href="/"><ArrowLeft size={16}/> Kembali</a><div className="ticket-detail"><div className="detail-head"><div><p className="eyebrow">SIG-{ticket.ticket_number}</p><h1 className="h1">{ticket.subject}</h1><p className="sub">Dibuat {new Date(ticket.created_at).toLocaleString("id-ID")} · {ticket.category?.name||"Tanpa kategori"}</p></div><span className={`badge ${ticket.status==='resolved'?'resolved':'open'}`}>{ticket.status}</span></div><div className="description"><strong>Deskripsi laporan</strong><p>{ticket.description}</p></div><div className="timeline"><h2 className="card-title">Percakapan</h2>{messages.length===0?<p className="sub">Belum ada balasan.</p>:messages.map(m=><div className="message" key={m.id}><div className="avatar">{(m.sender?.full_name||"U").slice(0,2).toUpperCase()}</div><div><strong>{m.sender?.full_name||"Pengguna"}</strong><small>{new Date(m.created_at).toLocaleString("id-ID")}</small><p>{m.body}</p></div></div>)}</div><form className="reply-box" onSubmit={send}><textarea required rows={4} value={body} onChange={e=>setBody(e.target.value)} placeholder="Tulis balasan..."/><button className="primary" disabled={sending}>{sending?<Loader2 className="spin" size={16}/>:<Send size={16}/>} Kirim balasan</button></form></div></main>}
