import type {
  AppData,
  Asset,
  AssetModel,
  AssetNote,
  Audit,
  Booking,
  Category,
  Custodian,
  CustomField,
  Kit,
  Location,
  Tag,
} from "./types";

/** Offset hari dari hari ini (negatif = masa lalu). */
function iso(days: number, hour = 9) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, days < 0 ? 14 : hour, 0, 0);
  return d.toISOString();
}

const ADMIN = "adminsystem";

const categories: Category[] = [
  {
    id: "gf-cat-it",
    name: "IT & Elektronik",
    description: "Laptop, printer, jaringan, perangkat digital",
    color: "#123367",
    createdAt: iso(-240),
  },
  {
    id: "gf-cat-kendaraan",
    name: "Kendaraan Operasional",
    description: "Mobil dinas, motor, kendaraan pabrik",
    color: "#3b82f6",
    createdAt: iso(-240),
  },
  {
    id: "gf-cat-produksi",
    name: "Mesin Produksi",
    description: "Line snack, oven, mixer, packing",
    color: "#CBA12C",
    createdAt: iso(-240),
  },
  {
    id: "gf-cat-qc",
    name: "Quality Control",
    description: "Alat ukur, timbangan, laboratorium",
    color: "#10b981",
    createdAt: iso(-230),
  },
  {
    id: "gf-cat-kantor",
    name: "Peralatan Kantor",
    description: "Meja, kursi, proyektor, sound",
    color: "#8b5cf6",
    createdAt: iso(-230),
  },
  {
    id: "gf-cat-gudang",
    name: "Gudang & Material Handling",
    description: "Forklift, pallet jack, racking",
    color: "#f59e0b",
    createdAt: iso(-220),
  },
  {
    id: "gf-cat-fasilitas",
    name: "Fasilitas Pabrik",
    description: "Utilitas, safety, pendingin",
    color: "#ef4444",
    createdAt: iso(-220),
  },
  {
    id: "gf-cat-marketing",
    name: "Marketing & Event",
    description: "Booth, kamera, merchandise kit",
    color: "#ec4899",
    createdAt: iso(-200),
  },
];

const tags: Tag[] = [
  {
    id: "gf-tag-prioritas",
    name: "Prioritas",
    color: "#ef4444",
    createdAt: iso(-200),
  },
  {
    id: "gf-tag-baru",
    name: "Baru 2025/2026",
    color: "#10b981",
    createdAt: iso(-180),
  },
  {
    id: "gf-tag-kalibrasi",
    name: "Perlu Kalibrasi",
    color: "#f59e0b",
    createdAt: iso(-180),
  },
  {
    id: "gf-tag-shared",
    name: "Shared Pool",
    color: "#3b82f6",
    createdAt: iso(-160),
  },
  {
    id: "gf-tag-haccp",
    name: "HACCP Critical",
    color: "#CBA12C",
    createdAt: iso(-160),
  },
  {
    id: "gf-tag-rusak",
    name: "Rusak Ringan",
    color: "#64748b",
    createdAt: iso(-140),
  },
];

const locations: Location[] = [
  {
    id: "gf-loc-hq",
    name: "Kantor Pusat Jakarta",
    description: "HQ Garudafood",
    address: "Bintaro Jaya, Tangerang Selatan",
    parentId: null,
    isParent: true,
    createdAt: iso(-250),
  },
  {
    id: "gf-loc-hq-it",
    name: "HQ — Lantai 5 IT",
    description: "Ruang server & helpdesk",
    address: "Kantor Pusat Lt.5",
    parentId: "gf-loc-hq",
    createdAt: iso(-250),
  },
  {
    id: "gf-loc-hq-meeting",
    name: "HQ — Ruang Meeting Garuda",
    description: "Ruang rapat direksi",
    address: "Kantor Pusat Lt.2",
    parentId: "gf-loc-hq",
    createdAt: iso(-250),
  },
  {
    id: "gf-loc-hq-mkt",
    name: "HQ — Lantai 3 Marketing",
    parentId: "gf-loc-hq",
    createdAt: iso(-250),
  },
  {
    id: "gf-loc-pati",
    name: "Pabrik Pati",
    description: "Pabrik snack utama",
    address: "Pati, Jawa Tengah",
    parentId: null,
    isParent: true,
    createdAt: iso(-250),
  },
  {
    id: "gf-loc-pati-line1",
    name: "Pati — Produksi Line 1",
    parentId: "gf-loc-pati",
    createdAt: iso(-250),
  },
  {
    id: "gf-loc-pati-qc",
    name: "Pati — Laboratorium QC",
    parentId: "gf-loc-pati",
    createdAt: iso(-250),
  },
  {
    id: "gf-loc-pati-gudang",
    name: "Pati — Gudang Finished Goods",
    parentId: "gf-loc-pati",
    createdAt: iso(-250),
  },
  {
    id: "gf-loc-rembang",
    name: "Pabrik Rembang",
    description: "Pabrik biskuit & wafer",
    address: "Rembang, Jawa Tengah",
    parentId: null,
    isParent: true,
    createdAt: iso(-240),
  },
  {
    id: "gf-loc-cikarang",
    name: "DC Cikarang",
    description: "Distribution center Jawa Barat",
    address: "MM2100, Cikarang",
    parentId: null,
    createdAt: iso(-240),
  },
  {
    id: "gf-loc-sby",
    name: "Cabang Surabaya",
    address: "Rungkut Industri, Surabaya",
    parentId: null,
    createdAt: iso(-230),
  },
];

const customFields: CustomField[] = [
  {
    id: "gf-cf-beli",
    name: "Tanggal Pembelian",
    type: "date",
    required: false,
    createdAt: iso(-200),
  },
  {
    id: "gf-cf-kondisi",
    name: "Kondisi",
    type: "option",
    required: false,
    options: ["Baik", "Cukup", "Rusak Ringan", "Rusak Berat"],
    createdAt: iso(-200),
  },
  {
    id: "gf-cf-tahun",
    name: "Tahun Perolehan",
    type: "number",
    required: false,
    createdAt: iso(-200),
  },
  {
    id: "gf-cf-costcenter",
    name: "Cost Center",
    type: "text",
    required: false,
    createdAt: iso(-190),
  },
];

const assetModels: AssetModel[] = [
  {
    id: "gf-mod-mba",
    name: 'MacBook Air M3 13"',
    brand: "Apple",
    modelNo: "MRXT3",
    categoryId: "gf-cat-it",
    createdAt: iso(-180),
  },
  {
    id: "gf-mod-x1",
    name: "ThinkPad X1 Carbon Gen 12",
    brand: "Lenovo",
    modelNo: "X1C-G12",
    categoryId: "gf-cat-it",
    createdAt: iso(-180),
  },
  {
    id: "gf-mod-epson",
    name: "Proyektor Epson EB-X51",
    brand: "Epson",
    modelNo: "EB-X51",
    categoryId: "gf-cat-kantor",
    createdAt: iso(-180),
  },
  {
    id: "gf-mod-avanza",
    name: "Toyota Avanza",
    brand: "Toyota",
    modelNo: "AVZ-2024",
    categoryId: "gf-cat-kendaraan",
    createdAt: iso(-170),
  },
  {
    id: "gf-mod-innova",
    name: "Toyota Kijang Innova Zenix",
    brand: "Toyota",
    modelNo: "ZNX-2025",
    categoryId: "gf-cat-kendaraan",
    createdAt: iso(-170),
  },
  {
    id: "gf-mod-forklift",
    name: "Toyota Forklift 2.5T",
    brand: "Toyota",
    modelNo: "8FBE25",
    categoryId: "gf-cat-gudang",
    createdAt: iso(-160),
  },
  {
    id: "gf-mod-timbang",
    name: "Timbangan Analitik Ohaus",
    brand: "Ohaus",
    modelNo: "PX224",
    categoryId: "gf-cat-qc",
    createdAt: iso(-160),
  },
  {
    id: "gf-mod-canon",
    name: "Kamera Canon EOS R50",
    brand: "Canon",
    modelNo: "EOS-R50",
    categoryId: "gf-cat-marketing",
    createdAt: iso(-150),
  },
];

const custodians: Custodian[] = [
  {
    id: "gf-cus-budi",
    name: "Budi Santoso",
    nik: "19900112001",
    department: "IT",
    email: "budi.santoso@garudafood.co.id",
    phone: "081234567890",
    createdAt: iso(-200),
  },
  {
    id: "gf-cus-siti",
    name: "Siti Aminah",
    nik: "19920304002",
    department: "Marketing",
    email: "siti.aminah@garudafood.co.id",
    phone: "081298765432",
    createdAt: iso(-200),
  },
  {
    id: "gf-cus-joko",
    name: "Joko Prasetyo",
    nik: "19881122003",
    department: "Produksi Pati",
    email: "joko.prasetyo@garudafood.co.id",
    phone: "081233445566",
    createdAt: iso(-190),
  },
  {
    id: "gf-cus-dewi",
    name: "Dewi Lestari",
    nik: "19950515004",
    department: "Finance",
    email: "dewi.lestari@garudafood.co.id",
    phone: "081212345678",
    createdAt: iso(-190),
  },
  {
    id: "gf-cus-ahmad",
    name: "Ahmad Fauzi",
    nik: "19910708005",
    department: "Quality Assurance",
    email: "ahmad.fauzi@garudafood.co.id",
    phone: "081276543210",
    createdAt: iso(-180),
  },
  {
    id: "gf-cus-rina",
    name: "Rina Kusuma",
    nik: "19961201006",
    department: "HRD",
    email: "rina.kusuma@garudafood.co.id",
    phone: "081255667788",
    createdAt: iso(-180),
  },
  {
    id: "gf-cus-hendra",
    name: "Hendra Wijaya",
    nik: "19870520007",
    department: "Warehouse",
    email: "hendra.wijaya@garudafood.co.id",
    phone: "081244556677",
    createdAt: iso(-170),
  },
  {
    id: "gf-cus-maya",
    name: "Maya Putri",
    nik: "19940811008",
    department: "Procurement",
    email: "maya.putri@garudafood.co.id",
    phone: "081233221100",
    createdAt: iso(-170),
  },
  {
    id: "gf-cus-andi",
    name: "Andi Saputra",
    nik: "19900228009",
    department: "Engineering",
    email: "andi.saputra@garudafood.co.id",
    phone: "081288990011",
    createdAt: iso(-160),
  },
  {
    id: "gf-cus-lina",
    name: "Lina Hartati",
    nik: "19930909010",
    department: "Sales Surabaya",
    email: "lina.hartati@garudafood.co.id",
    phone: "081277889900",
    createdAt: iso(-160),
  },
];

function note(
  assetId: string,
  content: string,
  type: string,
  daysAgo: number
): AssetNote {
  return {
    id: `gf-note-${assetId}-${type}`,
    assetId,
    content,
    type,
    createdAt: iso(daysAgo),
  };
}

function asset(
  partial: Omit<Asset, "notes" | "customValues" | "tagIds"> & {
    tagIds?: string[];
    customValues?: Record<string, string>;
    notes?: AssetNote[];
  }
): Asset {
  return {
    tagIds: [],
    customValues: {},
    notes: [],
    ...partial,
  };
}

const assets: Asset[] = [
  asset({
    id: "gf-ast-001",
    name: "MacBook Air M3 — IT 01",
    description: "Laptop helpdesk & development HQ",
    status: "AVAILABLE",
    categoryId: "gf-cat-it",
    locationId: "gf-loc-hq-it",
    assetModelId: "gf-mod-mba",
    custodianId: null,
    qrCode: "PIN-MBA001",
    value: 21500000,
    serialNumber: "C02-GF-MBA-001",
    tagIds: ["gf-tag-baru", "gf-tag-shared"],
    customValues: {
      "gf-cf-beli": "2025-11-12",
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2025",
      "gf-cf-costcenter": "IT-HQ",
    },
    notes: [
      note(
        "gf-ast-001",
        "Unit baru, SSD 512GB, sudah di-join domain GF.",
        "update",
        -40
      ),
    ],
    createdAt: iso(-40),
    updatedAt: iso(-2),
  }),
  asset({
    id: "gf-ast-002",
    name: "ThinkPad X1 — Dev 02",
    description: "Laptop backup developer",
    status: "CHECKED_OUT",
    categoryId: "gf-cat-it",
    locationId: "gf-loc-hq-it",
    assetModelId: "gf-mod-x1",
    custodianId: "gf-cus-budi",
    qrCode: "PIN-TP002",
    value: 24800000,
    serialNumber: "PF4-GF-X1-002",
    tagIds: ["gf-tag-prioritas"],
    customValues: {
      "gf-cf-beli": "2024-06-01",
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2024",
      "gf-cf-costcenter": "IT-HQ",
    },
    createdAt: iso(-280),
    updatedAt: iso(-6),
  }),
  asset({
    id: "gf-ast-003",
    name: "Proyektor Epson Ruang Garuda",
    description: "Proyektor tetap ruang meeting direksi",
    status: "CHECKED_OUT",
    categoryId: "gf-cat-kantor",
    locationId: "gf-loc-hq-meeting",
    assetModelId: "gf-mod-epson",
    custodianId: "gf-cus-siti",
    qrCode: "PIN-PRJ003",
    value: 8200000,
    serialNumber: "EPS-X51-003",
    tagIds: ["gf-tag-shared"],
    customValues: {
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2023",
      "gf-cf-costcenter": "GA-HQ",
    },
    createdAt: iso(-400),
    updatedAt: iso(-1),
  }),
  asset({
    id: "gf-ast-004",
    name: "Avanza Operasional HQ B 1234 GF",
    description: "Pool kendaraan HQ — antar-jemput meeting",
    status: "AVAILABLE",
    categoryId: "gf-cat-kendaraan",
    locationId: "gf-loc-hq",
    assetModelId: "gf-mod-avanza",
    qrCode: "PIN-AVZ004",
    value: 265000000,
    serialNumber: "B1234GF",
    tagIds: ["gf-tag-shared"],
    customValues: {
      "gf-cf-tahun": "2024",
      "gf-cf-kondisi": "Baik",
      "gf-cf-costcenter": "GA-HQ",
    },
    createdAt: iso(-320),
    updatedAt: iso(-10),
  }),
  asset({
    id: "gf-ast-005",
    name: "Innova Zenix Direksi B 88 GF",
    description: "Kendaraan direksi",
    status: "CHECKED_OUT",
    categoryId: "gf-cat-kendaraan",
    locationId: "gf-loc-hq",
    assetModelId: "gf-mod-innova",
    custodianId: "gf-cus-dewi",
    qrCode: "PIN-INV005",
    value: 520000000,
    serialNumber: "B88GF",
    tagIds: ["gf-tag-prioritas", "gf-tag-baru"],
    customValues: {
      "gf-cf-tahun": "2025",
      "gf-cf-kondisi": "Baik",
      "gf-cf-costcenter": "BOD",
    },
    createdAt: iso(-90),
    updatedAt: iso(-3),
  }),
  asset({
    id: "gf-ast-006",
    name: "Meja Standing Desk Ergonomis IT",
    description: "Meja listrik ruang IT",
    status: "MAINTENANCE",
    categoryId: "gf-cat-kantor",
    locationId: "gf-loc-hq-it",
    qrCode: "PIN-MEJ006",
    value: 4500000,
    serialNumber: "SD-IT-006",
    tagIds: ["gf-tag-rusak"],
    customValues: { "gf-cf-kondisi": "Rusak Ringan", "gf-cf-tahun": "2022" },
    notes: [
      note(
        "gf-ast-006",
        "Motor naik-turun macet, menunggu sparepart.",
        "maintenance",
        -4
      ),
    ],
    createdAt: iso(-500),
    updatedAt: iso(-4),
  }),
  asset({
    id: "gf-ast-007",
    name: "Sound System Portable Event",
    description: "Untuk gathering & launching produk",
    status: "AVAILABLE",
    categoryId: "gf-cat-marketing",
    locationId: "gf-loc-hq-mkt",
    qrCode: "PIN-SND007",
    value: 12500000,
    serialNumber: "SND-MKT-007",
    tagIds: ["gf-tag-shared"],
    customValues: {
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2023",
      "gf-cf-costcenter": "MKT",
    },
    createdAt: iso(-360),
    updatedAt: iso(-20),
  }),
  asset({
    id: "gf-ast-008",
    name: "Kamera Canon EOS R50 Marketing",
    description: "Dokumentasi campaign Chocolatos / Gery",
    status: "AVAILABLE",
    categoryId: "gf-cat-marketing",
    locationId: "gf-loc-hq-mkt",
    assetModelId: "gf-mod-canon",
    qrCode: "PIN-CAM008",
    value: 18900000,
    serialNumber: "CN-R50-008",
    tagIds: ["gf-tag-prioritas"],
    customValues: {
      "gf-cf-beli": "2025-03-18",
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2025",
    },
    createdAt: iso(-150),
    updatedAt: iso(-8),
  }),
  asset({
    id: "gf-ast-009",
    name: "Mixer Horizontal Line 1 Pati",
    description: "Mixer adonan snack Line 1",
    status: "AVAILABLE",
    categoryId: "gf-cat-produksi",
    locationId: "gf-loc-pati-line1",
    qrCode: "PIN-MIX009",
    value: 780000000,
    serialNumber: "MX-PTI-L1-009",
    tagIds: ["gf-tag-haccp", "gf-tag-prioritas"],
    customValues: {
      "gf-cf-tahun": "2019",
      "gf-cf-kondisi": "Baik",
      "gf-cf-costcenter": "PRD-PATI",
    },
    createdAt: iso(-1200),
    updatedAt: iso(-15),
  }),
  asset({
    id: "gf-ast-010",
    name: "Oven Tunnel Line 1 Pati",
    description: "Oven kontinu biskuit",
    status: "AVAILABLE",
    categoryId: "gf-cat-produksi",
    locationId: "gf-loc-pati-line1",
    qrCode: "PIN-OVN010",
    value: 1450000000,
    serialNumber: "OV-PTI-L1-010",
    tagIds: ["gf-tag-haccp", "gf-tag-prioritas"],
    customValues: {
      "gf-cf-tahun": "2018",
      "gf-cf-kondisi": "Cukup",
      "gf-cf-costcenter": "PRD-PATI",
    },
    createdAt: iso(-1400),
    updatedAt: iso(-12),
  }),
  asset({
    id: "gf-ast-011",
    name: "Packing Machine Vertical Pati",
    description: "VFFS kemasan Gery Saluut",
    status: "MAINTENANCE",
    categoryId: "gf-cat-produksi",
    locationId: "gf-loc-pati-line1",
    custodianId: "gf-cus-joko",
    qrCode: "PIN-PCK011",
    value: 620000000,
    serialNumber: "PK-PTI-011",
    tagIds: ["gf-tag-haccp", "gf-tag-rusak"],
    customValues: { "gf-cf-kondisi": "Rusak Ringan", "gf-cf-tahun": "2020" },
    notes: [
      note(
        "gf-ast-011",
        "Sealer temperature drift — dikalibrasi engineering.",
        "maintenance",
        -2
      ),
    ],
    createdAt: iso(-900),
    updatedAt: iso(-2),
  }),
  asset({
    id: "gf-ast-012",
    name: "Timbangan Analitik Ohaus QC Pati",
    description: "Timbangan lab 0.1 mg",
    status: "AVAILABLE",
    categoryId: "gf-cat-qc",
    locationId: "gf-loc-pati-qc",
    assetModelId: "gf-mod-timbang",
    qrCode: "PIN-TBG012",
    value: 28500000,
    serialNumber: "OH-PX224-012",
    tagIds: ["gf-tag-kalibrasi", "gf-tag-haccp"],
    customValues: {
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2022",
      "gf-cf-costcenter": "QA-PATI",
    },
    createdAt: iso(-600),
    updatedAt: iso(-18),
  }),
  asset({
    id: "gf-ast-013",
    name: "Moisture Analyzer QC Pati",
    description: "Uji kadar air bahan baku",
    status: "CHECKED_OUT",
    categoryId: "gf-cat-qc",
    locationId: "gf-loc-pati-qc",
    assetModelId: undefined,
    custodianId: "gf-cus-ahmad",
    qrCode: "PIN-MST013",
    value: 41000000,
    serialNumber: "MA-QC-013",
    tagIds: ["gf-tag-kalibrasi", "gf-tag-haccp"],
    customValues: { "gf-cf-kondisi": "Baik", "gf-cf-tahun": "2021" },
    createdAt: iso(-700),
    updatedAt: iso(-5),
  }),
  asset({
    id: "gf-ast-014",
    name: "pH Meter Laboratorium",
    description: "Pengukuran pH adonan & air proses",
    status: "AVAILABLE",
    categoryId: "gf-cat-qc",
    locationId: "gf-loc-pati-qc",
    qrCode: "PIN-PH014",
    value: 6500000,
    serialNumber: "PH-QC-014",
    tagIds: ["gf-tag-kalibrasi"],
    customValues: { "gf-cf-kondisi": "Baik", "gf-cf-tahun": "2023" },
    createdAt: iso(-450),
    updatedAt: iso(-30),
  }),
  asset({
    id: "gf-ast-015",
    name: "Forklift Elektrik 2.5T Gudang Pati",
    description: "Angkut FG ke racking",
    status: "AVAILABLE",
    categoryId: "gf-cat-gudang",
    locationId: "gf-loc-pati-gudang",
    assetModelId: "gf-mod-forklift",
    qrCode: "PIN-FRK015",
    value: 285000000,
    serialNumber: "TK-8FBE-015",
    tagIds: ["gf-tag-shared"],
    customValues: {
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2021",
      "gf-cf-costcenter": "WH-PATI",
    },
    createdAt: iso(-800),
    updatedAt: iso(-7),
  }),
  asset({
    id: "gf-ast-016",
    name: "Forklift Diesel Rembang",
    description: "Unit lama — dijadwalkan pensiun",
    status: "RETIRED",
    categoryId: "gf-cat-gudang",
    locationId: "gf-loc-rembang",
    qrCode: "PIN-FRK016",
    value: 150000000,
    serialNumber: "TK-DSL-016",
    tagIds: ["gf-tag-rusak"],
    customValues: { "gf-cf-kondisi": "Rusak Berat", "gf-cf-tahun": "2014" },
    notes: [
      note(
        "gf-ast-016",
        "Tidak layak operasi, suku cadang habis.",
        "retired",
        -25
      ),
    ],
    createdAt: iso(-2000),
    updatedAt: iso(-25),
  }),
  asset({
    id: "gf-ast-017",
    name: "Hand Pallet 2.5T — set 4 unit",
    description: "Pallet jack gudang FG Pati",
    status: "AVAILABLE",
    categoryId: "gf-cat-gudang",
    locationId: "gf-loc-pati-gudang",
    qrCode: "PIN-HPL017",
    value: 18000000,
    serialNumber: "HP-SET-017",
    tagIds: ["gf-tag-shared"],
    customValues: { "gf-cf-kondisi": "Cukup", "gf-cf-tahun": "2022" },
    createdAt: iso(-500),
    updatedAt: iso(-40),
  }),
  asset({
    id: "gf-ast-018",
    name: "Genset 500 kVA Pabrik Pati",
    description: "Backup listrik pabrik",
    status: "AVAILABLE",
    categoryId: "gf-cat-fasilitas",
    locationId: "gf-loc-pati",
    qrCode: "PIN-GEN018",
    value: 890000000,
    serialNumber: "GN-500-018",
    tagIds: ["gf-tag-prioritas"],
    customValues: {
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2017",
      "gf-cf-costcenter": "UTL-PATI",
    },
    createdAt: iso(-1600),
    updatedAt: iso(-21),
  }),
  asset({
    id: "gf-ast-019",
    name: "Chiller Process Water Pati",
    description: "Pendingin air proses Line 1–2",
    status: "AVAILABLE",
    categoryId: "gf-cat-fasilitas",
    locationId: "gf-loc-pati",
    qrCode: "PIN-CHL019",
    value: 410000000,
    serialNumber: "CH-PTI-019",
    tagIds: ["gf-tag-haccp"],
    customValues: { "gf-cf-kondisi": "Baik", "gf-cf-tahun": "2020" },
    createdAt: iso(-950),
    updatedAt: iso(-14),
  }),
  asset({
    id: "gf-ast-020",
    name: "APAR CO2 + Powder — set area produksi",
    description: "Alat pemadam kebakaran portable",
    status: "AVAILABLE",
    categoryId: "gf-cat-fasilitas",
    locationId: "gf-loc-pati-line1",
    qrCode: "PIN-APR020",
    value: 8500000,
    serialNumber: "APR-SET-020",
    tagIds: ["gf-tag-kalibrasi", "gf-tag-prioritas"],
    customValues: { "gf-cf-kondisi": "Baik", "gf-cf-tahun": "2024" },
    createdAt: iso(-200),
    updatedAt: iso(-9),
  }),
  asset({
    id: "gf-ast-021",
    name: "Laptop Dell Latitude — QA 03",
    description: "Laptop input hasil uji lab",
    status: "CHECKED_OUT",
    categoryId: "gf-cat-it",
    locationId: "gf-loc-pati-qc",
    custodianId: "gf-cus-ahmad",
    qrCode: "PIN-DLL021",
    value: 16200000,
    serialNumber: "DL-LAT-021",
    tagIds: ["gf-tag-shared"],
    customValues: {
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2023",
      "gf-cf-costcenter": "QA-PATI",
    },
    createdAt: iso(-420),
    updatedAt: iso(-5),
  }),
  asset({
    id: "gf-ast-022",
    name: "Printer Zebra Label Gudang",
    description: "Cetak label pallet FG",
    status: "AVAILABLE",
    categoryId: "gf-cat-it",
    locationId: "gf-loc-pati-gudang",
    qrCode: "PIN-ZBR022",
    value: 9800000,
    serialNumber: "ZB-ZT411-022",
    tagIds: ["gf-tag-shared"],
    customValues: { "gf-cf-kondisi": "Baik", "gf-cf-tahun": "2024" },
    createdAt: iso(-260),
    updatedAt: iso(-11),
  }),
  asset({
    id: "gf-ast-023",
    name: "Scanner Honeywell Gudang Cikarang",
    description: "Scan inbound/outbound DC",
    status: "AVAILABLE",
    categoryId: "gf-cat-it",
    locationId: "gf-loc-cikarang",
    qrCode: "PIN-HNW023",
    value: 4200000,
    serialNumber: "HW-CKR-023",
    tagIds: ["gf-tag-shared"],
    customValues: { "gf-cf-kondisi": "Baik", "gf-cf-tahun": "2024" },
    createdAt: iso(-210),
    updatedAt: iso(-16),
  }),
  asset({
    id: "gf-ast-024",
    name: "Pickup L300 Operasional Surabaya",
    description: "Distribusi sample & POSM Jawa Timur",
    status: "CHECKED_OUT",
    categoryId: "gf-cat-kendaraan",
    locationId: "gf-loc-sby",
    custodianId: "gf-cus-lina",
    qrCode: "PIN-L30024",
    value: 195000000,
    serialNumber: "L-1234SBY",
    tagIds: ["gf-tag-shared"],
    customValues: {
      "gf-cf-kondisi": "Cukup",
      "gf-cf-tahun": "2020",
      "gf-cf-costcenter": "SLS-SBY",
    },
    createdAt: iso(-850),
    updatedAt: iso(-1),
  }),
  asset({
    id: "gf-ast-025",
    name: "Booth Portable Launching Produk",
    description: "Booth lipat event ritel modern",
    status: "AVAILABLE",
    categoryId: "gf-cat-marketing",
    locationId: "gf-loc-hq-mkt",
    qrCode: "PIN-BTH025",
    value: 22000000,
    serialNumber: "BTH-MKT-025",
    tagIds: ["gf-tag-shared"],
    customValues: {
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2024",
      "gf-cf-costcenter": "MKT",
    },
    createdAt: iso(-300),
    updatedAt: iso(-22),
  }),
  asset({
    id: "gf-ast-026",
    name: "Metal Detector Line 1 Pati",
    description: "Deteksi kontaminan logam kemasan",
    status: "AVAILABLE",
    categoryId: "gf-cat-qc",
    locationId: "gf-loc-pati-line1",
    qrCode: "PIN-MTD026",
    value: 175000000,
    serialNumber: "MD-L1-026",
    tagIds: ["gf-tag-haccp", "gf-tag-kalibrasi", "gf-tag-prioritas"],
    customValues: {
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2021",
      "gf-cf-costcenter": "QA-PATI",
    },
    createdAt: iso(-780),
    updatedAt: iso(-6),
  }),
  asset({
    id: "gf-ast-027",
    name: "Laptop HP EliteBook — Procurement",
    description: "Laptop Maya Putri (procurement)",
    status: "CHECKED_OUT",
    categoryId: "gf-cat-it",
    locationId: "gf-loc-hq",
    custodianId: "gf-cus-maya",
    qrCode: "PIN-HP027",
    value: 17800000,
    serialNumber: "HP-EB-027",
    tagIds: ["gf-tag-baru"],
    customValues: {
      "gf-cf-beli": "2025-08-01",
      "gf-cf-kondisi": "Baik",
      "gf-cf-tahun": "2025",
    },
    createdAt: iso(-120),
    updatedAt: iso(-3),
  }),
  asset({
    id: "gf-ast-028",
    name: "Radio HT Safety Pabrik Pati (set 12)",
    description: "Komunikasi shift produksi & security",
    status: "AVAILABLE",
    categoryId: "gf-cat-fasilitas",
    locationId: "gf-loc-pati",
    qrCode: "PIN-HT028",
    value: 14400000,
    serialNumber: "HT-SET-028",
    tagIds: ["gf-tag-shared"],
    customValues: { "gf-cf-kondisi": "Baik", "gf-cf-tahun": "2023" },
    createdAt: iso(-380),
    updatedAt: iso(-19),
  }),
];

const kits: Kit[] = [
  {
    id: "gf-kit-001",
    name: "Paket Presentasi Direksi",
    description: "Laptop + proyektor + sound untuk rapat board",
    status: "AVAILABLE",
    qrCode: "KIT-DIR-001",
    assetIds: ["gf-ast-001", "gf-ast-003", "gf-ast-007"],
    categoryId: "gf-cat-kantor",
    locationId: "gf-loc-hq-meeting",
    createdAt: iso(-100),
  },
  {
    id: "gf-kit-002",
    name: "Paket Event Marketing",
    description: "Kamera + booth + sound launching produk",
    status: "AVAILABLE",
    qrCode: "KIT-MKT-002",
    assetIds: ["gf-ast-007", "gf-ast-008", "gf-ast-025"],
    categoryId: "gf-cat-marketing",
    locationId: "gf-loc-hq-mkt",
    createdAt: iso(-80),
  },
  {
    id: "gf-kit-003",
    name: "Paket Audit QC Lapangan",
    description: "Timbangan + pH meter + laptop QA",
    status: "AVAILABLE",
    qrCode: "KIT-QC-003",
    assetIds: ["gf-ast-012", "gf-ast-014", "gf-ast-021"],
    categoryId: "gf-cat-qc",
    locationId: "gf-loc-pati-qc",
    createdAt: iso(-60),
  },
];

const bookings: Booking[] = [
  {
    id: "gf-bk-001",
    name: "Peminjaman Proyektor — Rapat Brand Gery",
    description: "Presentasi campaign Q3 ke agency",
    status: "ONGOING",
    custodianId: "gf-cus-siti",
    fromDate: iso(-1, 8),
    toDate: iso(1, 18),
    assetIds: ["gf-ast-003"],
    kitIds: [],
    createdBy: ADMIN,
    createdAt: iso(-2),
    history: [{ status: "ONGOING", at: iso(-1), by: ADMIN }],
  },
  {
    id: "gf-bk-002",
    name: "Laptop IT — migrasi SAP",
    description: "Project cutover SAP MM",
    status: "OVERDUE",
    custodianId: "gf-cus-budi",
    fromDate: iso(-10, 8),
    toDate: iso(-2, 17),
    assetIds: ["gf-ast-002"],
    kitIds: [],
    createdBy: ADMIN,
    createdAt: iso(-11),
    history: [
      { status: "RESERVED", at: iso(-11), by: ADMIN },
      { status: "ONGOING", at: iso(-10), by: ADMIN },
    ],
  },
  {
    id: "gf-bk-003",
    name: "Innova — kunjungan pabrik Pati",
    description: "Direksi + finance site visit",
    status: "ONGOING",
    custodianId: "gf-cus-dewi",
    fromDate: iso(-3, 6),
    toDate: iso(2, 20),
    assetIds: ["gf-ast-005"],
    kitIds: [],
    createdBy: ADMIN,
    createdAt: iso(-5),
    history: [{ status: "ONGOING", at: iso(-3), by: ADMIN }],
  },
  {
    id: "gf-bk-004",
    name: "Moisture Analyzer — uji incoming tepung",
    description: "Lot incoming gandum Australia",
    status: "ONGOING",
    custodianId: "gf-cus-ahmad",
    fromDate: iso(-4, 7),
    toDate: iso(3, 16),
    assetIds: ["gf-ast-013"],
    kitIds: [],
    createdBy: ADMIN,
    createdAt: iso(-5),
    history: [{ status: "ONGOING", at: iso(-4), by: ADMIN }],
  },
  {
    id: "gf-bk-005",
    name: "L300 Surabaya — kunjungan ritel",
    description: "Tour Indomaret/Alfamart Jatim",
    status: "ONGOING",
    custodianId: "gf-cus-lina",
    fromDate: iso(-2, 7),
    toDate: iso(5, 18),
    assetIds: ["gf-ast-024"],
    kitIds: [],
    createdBy: ADMIN,
    createdAt: iso(-3),
    history: [{ status: "ONGOING", at: iso(-2), by: ADMIN }],
  },
  {
    id: "gf-bk-006",
    name: "Paket Event — launching Chocolatos variant",
    description: "Event mall Gandaria City",
    status: "RESERVED",
    custodianId: "gf-cus-siti",
    fromDate: iso(4, 8),
    toDate: iso(6, 21),
    assetIds: ["gf-ast-008", "gf-ast-025"],
    kitIds: ["gf-kit-002"],
    createdBy: ADMIN,
    createdAt: iso(-1),
    history: [{ status: "RESERVED", at: iso(-1), by: ADMIN }],
  },
  {
    id: "gf-bk-007",
    name: "Sound system — townhall karyawan",
    description: "Sudah selesai, dikembalikan lengkap",
    status: "COMPLETE",
    custodianId: "gf-cus-rina",
    fromDate: iso(-14, 8),
    toDate: iso(-13, 17),
    actualReturnDate: iso(-13, 16),
    returnCondition: "Baik, lengkap 2 mic + kabel",
    assetIds: ["gf-ast-007"],
    kitIds: [],
    createdBy: ADMIN,
    createdAt: iso(-16),
    history: [
      { status: "ONGOING", at: iso(-14), by: ADMIN },
      { status: "COMPLETE", at: iso(-13), by: ADMIN },
    ],
  },
  {
    id: "gf-bk-008",
    name: "Avanza pool — undangan vendor (batal)",
    description: "Vendor reschedule",
    status: "CANCELLED",
    custodianId: "gf-cus-maya",
    fromDate: iso(1, 8),
    toDate: iso(1, 18),
    assetIds: ["gf-ast-004"],
    kitIds: [],
    createdBy: ADMIN,
    createdAt: iso(-3),
    history: [
      { status: "RESERVED", at: iso(-3), by: ADMIN },
      { status: "CANCELLED", at: iso(-1), by: ADMIN },
    ],
  },
  {
    id: "gf-bk-009",
    name: "Laptop Procurement — tender kemasan",
    description: "Tender film BOPP",
    status: "ONGOING",
    custodianId: "gf-cus-maya",
    fromDate: iso(-7, 8),
    toDate: iso(7, 17),
    assetIds: ["gf-ast-027"],
    kitIds: [],
    createdBy: ADMIN,
    createdAt: iso(-8),
    history: [{ status: "ONGOING", at: iso(-7), by: ADMIN }],
  },
];

const audits: Audit[] = [
  {
    id: "gf-aud-001",
    name: "Audit Q1 — Gudang FG Pati",
    status: "OPEN",
    createdBy: ADMIN,
    createdAt: iso(-3),
    items: [
      {
        id: "gf-ai-001",
        auditId: "gf-aud-001",
        assetId: "gf-ast-015",
        result: "FOUND",
        note: "Ada di charging bay, jam 07.10",
        scannedAt: iso(-2, 7),
      },
      {
        id: "gf-ai-002",
        auditId: "gf-aud-001",
        assetId: "gf-ast-017",
        result: null,
      },
      {
        id: "gf-ai-003",
        auditId: "gf-aud-001",
        assetId: "gf-ast-022",
        result: "FOUND",
        scannedAt: iso(-2, 8),
      },
      {
        id: "gf-ai-004",
        auditId: "gf-aud-001",
        assetId: "gf-ast-016",
        result: "MISSING",
        note: "Unit retired, fisik sudah di scrap yard Rembang",
        scannedAt: iso(-2, 9),
      },
    ],
  },
  {
    id: "gf-aud-002",
    name: "Audit IT — Kantor Pusat Lt.5",
    status: "COMPLETED",
    createdBy: ADMIN,
    createdAt: iso(-20),
    items: [
      {
        id: "gf-ai-005",
        auditId: "gf-aud-002",
        assetId: "gf-ast-001",
        result: "FOUND",
        scannedAt: iso(-19, 10),
      },
      {
        id: "gf-ai-006",
        auditId: "gf-aud-002",
        assetId: "gf-ast-002",
        result: "FOUND",
        note: "Sedang dibawa Budi (booking aktif)",
        scannedAt: iso(-19, 10),
      },
      {
        id: "gf-ai-007",
        auditId: "gf-aud-002",
        assetId: "gf-ast-006",
        result: "DAMAGED",
        note: "Meja standing, motor rusak",
        scannedAt: iso(-19, 11),
      },
    ],
  },
];

/** Data contoh lengkap — situs & aset khas operasional Garudafood. */
export const seedData: AppData = {
  categories,
  tags,
  locations,
  customFields,
  assetModels,
  custodians,
  assets,
  kits,
  bookings,
  audits,
};
