import type { Ticket } from "./tickets";

function iso(days: number, hour = 10) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, Math.abs(days * 7) % 50, 0, 0);
  return d.toISOString();
}

/**
 * Tiket helpdesk contoh — karyawan & isu khas operasional Garudafood.
 * Beberapa taut ke aset demo (gf-ast-*) supaya panel Ticketing langsung
 * nyambung ke modul aset SIGAP.
 */
export function buildDemoTickets(): Ticket[] {
  return [
    {
      id: "tck_gf_001",
      number: "TKT-GF8K2A",
      name: "Budi Santoso",
      email: "budi.santoso@garudafood.co.id",
      phone: "081234567890",
      category: "Aset & IT",
      subject: "ThinkPad X1 sering blue screen saat cutover SAP",
      message:
        "Laptop IT 02 (ThinkPad X1) restart sendiri 3x sejak kemarin saat buka SAP GUI. Sudah restart & update Windows. Mohon dicek sebelum go-live MM hari Jumat.",
      status: "IN_PROGRESS",
      adminNote: "Sudah remote. Suspect RAM. Tunggu spare SODIMM dari vendor.",
      assetId: "gf-ast-002",
      createdAt: iso(-2, 8),
      updatedAt: iso(-1, 16),
    },
    {
      id: "tck_gf_002",
      number: "TKT-GF3N7P",
      name: "Siti Aminah",
      email: "siti.aminah@garudafood.co.id",
      phone: "081298765432",
      category: "Aset & IT",
      subject: "Proyektor Ruang Garuda tidak nyala",
      message:
        "Mau rapat campaign Gery jam 14.00. Proyektor Epson di Ruang Meeting Garuda lampu oranye, tidak ada sinyal HDMI dari laptop agency.",
      status: "OPEN",
      adminNote: "",
      assetId: "gf-ast-003",
      createdAt: iso(0, 9),
      updatedAt: iso(0, 9),
    },
    {
      id: "tck_gf_003",
      number: "TKT-GF9Q4C",
      name: "Joko Prasetyo",
      email: "joko.prasetyo@garudafood.co.id",
      phone: "081233445566",
      category: "Aset & IT",
      subject: "Packing machine Line 1 error sealer temperature",
      message:
        "VFFS Gery Saluut Line 1 Pati alarm suhu sealer. Produksi tertahan sejak shift 1. Engineering sudah lihat, mohon tiket resmi + status aset di SIGAP.",
      status: "IN_PROGRESS",
      adminNote:
        "Aset PIN-PCK011 sudah MAINTENANCE. Teknisi vendor datang sore.",
      assetId: "gf-ast-011",
      createdAt: iso(-1, 6),
      updatedAt: iso(0, 7),
    },
    {
      id: "tck_gf_004",
      number: "TKT-GF2H8M",
      name: "Ahmad Fauzi",
      email: "ahmad.fauzi@garudafood.co.id",
      phone: "081276543210",
      category: "Aset & IT",
      subject: "Timbangan analitik Ohaus perlu kalibrasi ulang",
      message:
        "Hasil uji kadar air lot tepung Australia tidak konsisten vs lab Rembang. Mohon jadwalkan kalibrasi Ohaus PX224 di Lab QC Pati sebelum audit HACCP.",
      status: "OPEN",
      adminNote: "",
      assetId: "gf-ast-012",
      createdAt: iso(-1, 11),
      updatedAt: iso(-1, 11),
    },
    {
      id: "tck_gf_005",
      number: "TKT-GF5R1D",
      name: "Hendra Wijaya",
      email: "hendra.wijaya@garudafood.co.id",
      phone: "081244556677",
      category: "Aset & IT",
      subject: "Printer Zebra gudang FG tidak cetak label pallet",
      message:
        "Zebra ZT411 di Gudang Finished Goods Pati error ribbon. Stok label masih ada. Butuh ganti ribbon + cek driver SAP EWM.",
      status: "RESOLVED",
      adminNote:
        "Ribbon diganti, print test 20 label OK. Tutup tiket setelah shift 2 konfirmasi.",
      assetId: "gf-ast-022",
      createdAt: iso(-5, 7),
      updatedAt: iso(-3, 15),
    },
    {
      id: "tck_gf_006",
      number: "TKT-GF7W3B",
      name: "Maya Putri",
      email: "maya.putri@garudafood.co.id",
      phone: "081233221100",
      category: "Aset & IT",
      subject: "Tidak bisa akses folder share tender kemasan",
      message:
        "Folder \\\\gf-file\\procurement\\tender-bopp tidak bisa dibuka dari laptop EliteBook. Error access denied. Butuh akses read/write untuk tender film BOPP minggu ini.",
      status: "IN_PROGRESS",
      adminNote: "Request AD group PROC-TENDER sudah diajukan ke IT Security.",
      assetId: "gf-ast-027",
      createdAt: iso(-3, 13),
      updatedAt: iso(-2, 9),
    },
    {
      id: "tck_gf_007",
      number: "TKT-GF4P6K",
      name: "Rina Kusuma",
      email: "rina.kusuma@garudafood.co.id",
      phone: "081255667788",
      category: "Fasilitas / Gedung",
      subject: "AC lantai 3 Marketing tidak dingin",
      message:
        "Ruang Marketing HQ Lt.3 panas sejak Senin. Suhu sekitar 29°C. Tim sudah 18 orang, meeting agency jadi tidak nyaman.",
      status: "OPEN",
      adminNote: "",
      createdAt: iso(-1, 8),
      updatedAt: iso(-1, 8),
    },
    {
      id: "tck_gf_008",
      number: "TKT-GF6T2F",
      name: "Dewi Lestari",
      email: "dewi.lestari@garudafood.co.id",
      phone: "081212345678",
      category: "Fasilitas / Gedung",
      subject: "Kartu akses basement mobil direksi error",
      message:
        "Kartu tap Innova B 88 GF tidak membuka palang basement HQ. Security minta tiket ke GA/IT akses.",
      status: "RESOLVED",
      adminNote: "Kartu di-reprogram di sistem C3. Tes tap 3x berhasil.",
      assetId: "gf-ast-005",
      createdAt: iso(-6, 7),
      updatedAt: iso(-5, 11),
    },
    {
      id: "tck_gf_009",
      number: "TKT-GF1J9S",
      name: "Andi Saputra",
      email: "andi.saputra@garudafood.co.id",
      phone: "081288990011",
      category: "Fasilitas / Gedung",
      subject: "Lampu emergency Line 1 Pati beberapa titik mati",
      message:
        "Audit safety minggu depan. 4 titik emergency lamp di area oven tunnel tidak nyala saat tes. Mohon penggantian baterai/unit.",
      status: "IN_PROGRESS",
      adminNote: "PO baterai ke vendor safety. Estimasi datang 2 hari.",
      createdAt: iso(-4, 9),
      updatedAt: iso(-1, 14),
    },
    {
      id: "tck_gf_010",
      number: "TKT-GF8C5V",
      name: "Lina Hartati",
      email: "lina.hartati@garudafood.co.id",
      phone: "081277889900",
      category: "Aset & IT",
      subject: "L300 Surabaya servis — minta mobil pengganti",
      message:
        "Pickup L300 bunyi aneh di bagian kopling saat tour Indomaret Jatim. Bisa diservis di bengkel resmi? Sales butuh unit cadangan 3 hari.",
      status: "OPEN",
      adminNote: "",
      assetId: "gf-ast-024",
      createdAt: iso(0, 7),
      updatedAt: iso(0, 7),
    },
    {
      id: "tck_gf_011",
      number: "TKT-GF2M8Y",
      name: "Budi Santoso",
      email: "budi.santoso@garudafood.co.id",
      phone: "081234567890",
      category: "Aset & IT",
      subject: "Meja standing desk IT macet — tidak naik",
      message:
        "Meja listrik ruang IT HQ tidak bisa dinaikkan. Motor bunyi klik. Mohon teknisi furniture / ganti unit.",
      status: "IN_PROGRESS",
      adminNote: "Aset PIN-MEJ006 sudah MAINTENANCE. Sparepart dipesan.",
      assetId: "gf-ast-006",
      createdAt: iso(-4, 10),
      updatedAt: iso(-2, 15),
    },
    {
      id: "tck_gf_012",
      number: "TKT-GF9D3H",
      name: "Siti Aminah",
      email: "siti.aminah@garudafood.co.id",
      phone: "081298765432",
      category: "Umum",
      subject: "Request konsumsi rapat launching Chocolatos",
      message:
        "Rapat agency + internal marketing Kamis, 12 orang. Mohon snack Gery + air mineral di Ruang Garuda jam 13.30.",
      status: "RESOLVED",
      adminNote: "GA sudah siapkan. Tiket ditutup.",
      createdAt: iso(-8, 11),
      updatedAt: iso(-7, 9),
    },
    {
      id: "tck_gf_013",
      number: "TKT-GF4K7N",
      name: "Hendra Wijaya",
      email: "hendra.wijaya@garudafood.co.id",
      phone: "081244556677",
      category: "Fasilitas / Gedung",
      subject: "Atap kanopi loading dock Pati bocor",
      message:
        "Hujan semalam, area loading dock FG basah. Karton kemasan rawan lembap. Mohon perbaikan kanopi segera.",
      status: "OPEN",
      adminNote: "",
      createdAt: iso(0, 6),
      updatedAt: iso(0, 6),
    },
    {
      id: "tck_gf_014",
      number: "TKT-GF6B2Q",
      name: "Ahmad Fauzi",
      email: "ahmad.fauzi@garudafood.co.id",
      phone: "081276543210",
      category: "Aset & IT",
      subject: "Metal detector Line 1 false reject tinggi",
      message:
        "Metal detector PIN-MTD026 reject 8% kemasan tanpa kontaminan. Produksi Gery terganggu. Mohon kalibrasi + cek coil.",
      status: "OPEN",
      adminNote: "",
      assetId: "gf-ast-026",
      createdAt: iso(-1, 15),
      updatedAt: iso(-1, 15),
    },
    {
      id: "tck_gf_015",
      number: "TKT-GF3F8W",
      name: "Rina Kusuma",
      email: "rina.kusuma@garudafood.co.id",
      phone: "081255667788",
      category: "Umum",
      subject: "Onboarding karyawan baru — akun email & VPN",
      message:
        "3 karyawan baru Produksi Pati mulai Senin. Mohon buatkan email @garudafood.co.id, akun SAP display, dan VPN. Nama sudah di email HRD kemarin.",
      status: "CLOSED",
      adminNote: "3 akun dibuat, password dikirim via WhatsApp HRD. Closed.",
      createdAt: iso(-12, 9),
      updatedAt: iso(-10, 16),
    },
    {
      id: "tck_gf_016",
      number: "TKT-GF8P5T",
      name: "Andi Saputra",
      email: "andi.saputra@garudafood.co.id",
      phone: "081288990011",
      category: "Lainnya",
      subject: "Radio HT shift malam beberapa unit tidak charge",
      message:
        "Dari set 12 HT safety Pati, 3 unit tidak mau ngecas di docking. Shift malam kesulitan komunikasi ke security.",
      status: "IN_PROGRESS",
      adminNote: "3 unit ditarik ke engineering. Docking bay dicek tegangan.",
      assetId: "gf-ast-028",
      createdAt: iso(-2, 18),
      updatedAt: iso(-1, 8),
    },
    {
      id: "tck_gf_017",
      number: "TKT-GF1V4E",
      name: "Lina Hartati",
      email: "lina.hartati@garudafood.co.id",
      phone: "081277889900",
      category: "Umum",
      subject: "Request sample POSM untuk toko modern Surabaya",
      message:
        "Butuh 20 pack dummy Chocolatos + standing banner untuk display Indomaret Rungkut. Bisa diambil di DC atau dikirim ekspedisi?",
      status: "RESOLVED",
      adminNote: "Dikirim via L300. Diterima Lina 14.20.",
      createdAt: iso(-9, 10),
      updatedAt: iso(-7, 15),
    },
    {
      id: "tck_gf_018",
      number: "TKT-GF7N9A",
      name: "Dewi Lestari",
      email: "dewi.lestari@garudafood.co.id",
      phone: "081212345678",
      category: "Aset & IT",
      subject: "VPN putus saat approve pembayaran vendor",
      message:
        "VPN HQ sering disconnect sejak kemarin sore. Gagal approve Fiori. Mohon cek gateway.",
      status: "CLOSED",
      adminNote: "Restart concentrator VPN. Monitoring 24 jam stabil. Closed.",
      createdAt: iso(-11, 16),
      updatedAt: iso(-10, 9),
    },
  ];
}
